# admin-user-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: admin-user-token-secret # Nome que você vai usar para referenciar
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: admin-user # Associa ao ServiceAccount 'admin-user'
type: kubernetes.io/service-account-token